dataset:
  name: CIFAR100
  batch_size: 256
model:
  backbone: ResNet18SSL
  pretrained: true
  normalize: false
  activation: lin
incremental:
  num_tasks: 10
  classes_per_task: 10
  initial_tasks: 1
  samples_per_task: null
  buffer_size: 2000
  use_eb: true
  sampling_strategy: random
training:
  use_wandb: false
output_dir: "./results/CIFAR100_ResNet18SSL/pretrained"
device: "cuda"
