dataset:
  name: CIFAR100
  batch_size: 256
model:
  backbone: ViTB16
  pretrained: true
  activation: lin
  normalize: true
  lamb: 0.01
incremental:
  num_tasks: 10
  classes_per_task: 10
  initial_tasks: 1
  samples_per_task: null
  buffer_size: 2000
  use_eb: true
  sampling_strategy: random
  replay_backend: buffer
training:
  use_wandb: False
output_dir: "./results/CIFAR100_ViT/normalize2"
device: "cuda"
