dataset:
  name: CIFAR100
  batch_size: 256
model:
  backbone: ResNet34
  pretrained: true
  learning_rate: 0.001
  freeze_mode: all
rolann:
  rolann_lamb: 0.01
  sparse: false
  dropout_rate: 0.0
  freeze_rolann: false
incremental:
  num_tasks: 20
  classes_per_task: 5
  initial_tasks: 1
  samples_per_task: null
  buffer_size: 200
  use_eb: true
  sampling_strategy: random
training:
  epochs: 10
  use_wandb: false
  patience: null
output_dir: "experiments/experiments_04_11/CIFAR100_k20"
device: "cuda"
