dataset:
  name: ImageFolder
  root: /home/alejandrodopico/data/ImageNet100
  batch_size: 256
model:
  backbone: ResNet18SSL
  pretrained: true
  normalize: false
  activation: logs
incremental:
  num_tasks: 20
  classes_per_task: 5
  initial_tasks: 1
  samples_per_task: null
  buffer_size: 2000
  use_eb: true
  sampling_strategy: random
training:
  use_wandb: True
output_dir: "./results/ImageNet100_ResNet18SSL/pretrained"
device: "cuda"
