dataset:
  name: TinyImageNet
  batch_size: 256
model:
  backbone: ResNet
  pretrained: true
  learning_rate: 0.001
  freeze_mode: all
rolann:
  rolann_lamb: 0.01
  sparse: false
  dropout_rate: 0.0
  freeze_rolann: false
incremental:
  num_tasks: 2
  classes_per_task: 100
  samples_per_task: null
  buffer_size: 200
  use_eb: true
  sampling_strategy: random
training:
  epochs: 1
  use_wandb: false
  patience: null
output_dir: "experiments/experiments_11_12/TinyImageNet_k2"
device: "cuda"
