from collections import defaultdict
from typing import Any, Dict, List, Optional, Tuple

import torch
import torch.nn.functional as F
from loguru import logger

from models.replay.EmbeddingCVAE import EmbeddingCVAE
from models.replay.utils import upsample_per_class
from models.samplers.SamplingStrategy import HerdingSampling

# Import lazily to avoid circular dependency at module load time.
def _generation_report(real_by_class, gen_by_class):
    from models.replay.cvae_metrics import per_class_generation_report
    return per_class_generation_report(real_by_class, gen_by_class)


class EmbeddingReplayStore:
    """
    Replay store backed by a class-conditional CVAE operating in embedding space.

    Two operating modes are supported via the ``use_real_buffer`` flag:

    ``use_real_buffer=True``  (cvae_hybrid / cvae_full  — backward-compatible)
        A real exemplar buffer is maintained alongside the CVAE.  Replay
        prefers stored real embeddings and uses the CVAE only to fill up to
        the requested per-class count.  This is the original hybrid design.

    ``use_real_buffer=False``  (cvae_pure — new, buffer-free)
        No real embeddings are stored for classifier replay.  The CVAE is the
        sole source of old-class embeddings.  During ``maintain()``, the
        current task's real embeddings (held in ``_task_pool``) are combined
        with synthetic old-class embeddings generated by the previous CVAE
        snapshot to form a class-balanced training set before CVAE fitting.
        ``get_memory_samples()`` always calls the CVAE directly; there is no
        quality-gate fallback to stored reals.

    Catastrophic-forgetting prevention inside the CVAE
    ---------------------------------------------------
    Two mechanisms work in concert:

    1.  **Pre-balanced synthetic replay** — before fitting the CVAE on the new
        task, ``maintain()`` generates exactly  N  synthetic embeddings per old
        class from the previous CVAE snapshot (where N equals the per-class
        sample count of the current task).  This ensures every old class is
        equally represented in the CVAE training set regardless of the total
        number of accumulated classes.

    2.  **Teacher KL distillation** (optional, ``use_teacher_kl=True``) — the
        student CVAE's posterior is penalised for diverging from the frozen
        teacher's posterior on the same inputs.  This is passed through to
        ``EmbeddingCVAE.fit()`` and is independent of mode.
    """

    def __init__(
        self,
        embed_dim: int = 768,
        memory_size: int = 2000,
        anchor_per_class: int = 5,
        generated_per_class: int = 15,
        latent_dim: int = 64,
        class_embed_dim: int = 64,
        hidden_dim: int = 256,
        train_steps: int = 2000,
        train_min_steps: int = 50,
        train_eval_every: int = 20,
        train_patience: int = 3,
        recon_cosine_stop: float = 0.93,
        gen_cosine_stop: float = 0.88,
        gen_eval_samples_per_class: int = 32,
        train_on: str = "real_buffer",
        beta: float = 0.05,
        gen_replay_ratio: float = 0.3,
        use_teacher_kl: bool = False,
        teacher_kl_weight: float = 0.1,
        device: str = "cuda",
        max_classes: int = 1000,
        stats_loss_weight: float = 0.01,
        feature_matching_weight: float = 0.1,
        replay_debug: bool = False,
        normalize_embeddings: bool = True,
        kl_anneal_steps: int = 200,
        beta_floor: float = 1e-4,
        use_real_buffer: bool = True,
        ref_buffer_per_class: int = 0,
        min_sampling_std: float = 0.2,
        ref_buffer_anchor_cvae: bool = False,
    ):
        self.embed_dim = embed_dim
        self.memory_size = memory_size
        self.latent_dim = latent_dim
        self.class_embed_dim = class_embed_dim
        self.hidden_dim = hidden_dim
        self.anchor_per_class = anchor_per_class
        self.generated_per_class = generated_per_class
        self.train_max_steps = train_steps
        self.train_min_steps = train_min_steps
        self.train_eval_every = train_eval_every
        self.train_patience = train_patience
        self.recon_cosine_stop = recon_cosine_stop
        self.gen_cosine_stop = gen_cosine_stop
        self.gen_eval_samples_per_class = gen_eval_samples_per_class
        self.train_on = train_on
        self.beta = beta
        self.gen_replay_ratio = gen_replay_ratio
        self.use_teacher_kl = use_teacher_kl
        self.teacher_kl_weight = teacher_kl_weight
        self.device = torch.device(device)
        self.stats_loss_weight = stats_loss_weight
        self.feature_matching_weight = feature_matching_weight
        self.replay_debug = replay_debug
        self.normalize_embeddings = normalize_embeddings
        self.kl_anneal_steps = kl_anneal_steps
        self.beta_floor = beta_floor
        self.use_real_buffer = use_real_buffer
        self._ref_buffer_max_per_class = ref_buffer_per_class
        self.min_sampling_std = min_sampling_std
        # When True and ref_buffer_per_class > 0, real reference samples are
        # mixed into the CVAE training data for old classes.  This prevents
        # compounding centroid drift across tasks without storing real data for
        # the ROLANN classifier.  Requires ref_buffer_per_class > 0.
        self._ref_buffer_anchor_cvae = ref_buffer_anchor_cvae

        # Real exemplar buffer — used only when use_real_buffer=True.
        self.real_buffer: Dict[int, torch.Tensor] = defaultdict(
            lambda: torch.empty(0)
        )

        # Measurement-only reference buffer: stores up to *ref_buffer_per_class*
        # real embeddings per class.  Never used for CVAE training or ROLANN
        # replay — purely for generation quality diagnostics.
        self._ref_buffer: Dict[int, torch.Tensor] = {}

        # Current-task staging area: populated by add_task_samples() and
        # cleared after maintain().  Always used (both modes) for CVAE training.
        self._task_pool: Dict[int, torch.Tensor] = defaultdict(
            lambda: torch.empty(0)
        )

        # Herding anchors — used only when use_real_buffer=True and
        # anchor_per_class > 0.
        self.anchors: Dict[int, torch.Tensor] = {}

        self.class_means: Dict[int, torch.Tensor] = {}
        self.class_vars: Dict[int, torch.Tensor] = {}
        self.class_counts: Dict[int, int] = defaultdict(int)

        self._herding = HerdingSampling(normalize=normalize_embeddings)
        self._cvae: Optional[EmbeddingCVAE] = None
        self._max_classes = max_classes
        self._cvae_trained = False
        self._max_class_id = 0
        self.last_replay_sources: Dict[int, Dict[str, int]] = {}
        self.last_cvae_fit_summary: Dict[str, Any] = {}

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _normalize(self, x: torch.Tensor) -> torch.Tensor:
        x = x.float()
        if self.normalize_embeddings:
            return F.normalize(x, p=2, dim=-1)
        return x

    def _cvae_replay_ready(self) -> bool:
        """
        Quality gate for real-buffer mode.  Always True in buffer-free mode
        (we commit fully to the CVAE after training).
        """
        if not self._cvae_trained:
            return False
        if not self.use_real_buffer:
            return True
        summary = self.last_cvae_fit_summary
        if not summary:
            return False
        return float(summary.get("recon_cosine", 0.0)) >= self.recon_cosine_stop

    def _max_known_class(self) -> int:
        keys = (
            list(self.real_buffer.keys())
            + list(self.anchors.keys())
            + list(self._task_pool.keys())
        )
        if not keys:
            return self._max_class_id
        return max(max(keys), self._max_class_id)

    def _ensure_cvae(self) -> EmbeddingCVAE:
        n = max(self._max_known_class() + 1, 1)
        if self._cvae is None:
            self._cvae = EmbeddingCVAE(
                embed_dim=self.embed_dim,
                num_classes=min(n, self._max_classes),
                latent_dim=self.latent_dim,
                class_embed_dim=self.class_embed_dim,
                hidden_dim=self.hidden_dim,
                normalize_embeddings=self.normalize_embeddings,
                kl_anneal_steps=self.kl_anneal_steps,
                beta_floor=self.beta_floor,
                min_sampling_std=self.min_sampling_std,
            ).to(self.device)
        elif n > self._cvae.num_classes:
            self._cvae._expand_classes(min(n, self._max_classes))
        return self._cvae

    def _update_class_stats(
        self, embeddings: torch.Tensor, labels: torch.Tensor
    ) -> None:
        z = self._normalize(embeddings.detach().cpu())
        for c in labels.unique().tolist():
            c = int(c)
            mask = labels == c
            batch = z[mask]
            if batch.numel() == 0:
                continue
            batch_mean = batch.mean(dim=0)
            batch_var = batch.var(dim=0, unbiased=False).clamp(min=1e-6)
            n = batch.size(0)
            prev_n = self.class_counts[c]
            if prev_n == 0 or c not in self.class_means:
                self.class_means[c] = batch_mean
                self.class_vars[c] = batch_var
            else:
                total = prev_n + n
                self.class_means[c] = (
                    self.class_means[c] * prev_n + batch_mean * n
                ) / total
                self.class_vars[c] = (
                    self.class_vars[c] * prev_n + batch_var * n
                ) / total
            self.class_counts[c] = prev_n + n

    def _maintain_real_buffer(self) -> None:
        """Balanced quota policy for the real exemplar buffer (hybrid/full modes)."""
        if not self.real_buffer:
            return
        num_classes = len(self.real_buffer)
        quota = max(1, self.memory_size // num_classes)
        for cls in list(self.real_buffer.keys()):
            tensor = self.real_buffer[cls]
            if tensor.size(0) > quota:
                self.real_buffer[cls] = self._herding.sample(tensor, quota)

    def _update_anchors(self) -> None:
        if self.anchor_per_class <= 0:
            return
        for cls, pool in self._task_pool.items():
            if pool.numel() == 0:
                continue
            pool = self._normalize(pool)
            selected = self._herding.sample(pool, self.anchor_per_class)
            self.anchors[cls] = selected.cpu()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def add_task_samples(
        self, embeddings: torch.Tensor, labels: torch.Tensor
    ) -> None:
        """
        Stage embeddings for CVAE training.

        Always populates ``_task_pool`` (used as current-task training data
        for the CVAE in ``maintain()``).  Also populates ``real_buffer`` when
        ``use_real_buffer=True``.
        """
        embeddings = self._normalize(embeddings.detach().cpu())
        if embeddings.ndim == 1:
            embeddings = embeddings.unsqueeze(0)
        labels = labels.detach().cpu().long().view(-1)

        if embeddings.size(0) != labels.size(0):
            labels = labels.expand(embeddings.size(0))

        self.embed_dim = embeddings.size(1)
        self._update_class_stats(embeddings, labels)

        for c in labels.unique().tolist():
            c = int(c)
            self._max_class_id = max(self._max_class_id, c)
            mask = labels == c
            batch = embeddings[mask]
            if batch.ndim == 1:
                batch = batch.unsqueeze(0)

            prev_pool = self._task_pool[c]
            self._task_pool[c] = (
                batch
                if prev_pool.numel() == 0
                else torch.cat([prev_pool, batch], dim=0)
            )

            if self.use_real_buffer:
                prev_real = self.real_buffer[c]
                self.real_buffer[c] = (
                    batch
                    if prev_real.numel() == 0
                    else torch.cat([prev_real, batch], dim=0)
                )

            # Measurement-only reference buffer: fill greedily up to the cap.
            # Since the dataloader is shuffled, the first N rows are a valid
            # random sample.  The buffer is NEVER cleared — it accumulates a
            # snapshot of every class seen so far for quality diagnostics.
            if self._ref_buffer_max_per_class > 0:
                existing = self._ref_buffer.get(c)
                if existing is None or existing.numel() == 0:
                    self._ref_buffer[c] = batch[: self._ref_buffer_max_per_class]
                elif existing.size(0) < self._ref_buffer_max_per_class:
                    remaining = self._ref_buffer_max_per_class - existing.size(0)
                    self._ref_buffer[c] = torch.cat([existing, batch[:remaining]], 0)
                # else: already full — skip to avoid bias from later batches

    def maintain(self) -> None:
        """
        Update the CVAE after each incremental task.

        Steps
        -----
        1.  (real-buffer mode only) Trim the real buffer to the balanced quota
            and update herding anchors.
        2.  Build the CVAE training tensor.
            - Real-buffer mode: uses the stored real exemplars + anchors
              (same behaviour as before).
            - Buffer-free mode: uses only ``_task_pool`` (current task's real
              embeddings) plus teacher-generated synthetic embeddings for every
              old class, in a quantity that matches the current task's per-class
              sample count.  This produces a perfectly balanced training set.
        3.  Fit the CVAE.  Teacher KL distillation is applied when enabled.
        4.  Clear ``_task_pool``.
        """
        if self.use_real_buffer:
            self._maintain_real_buffer()
            self._update_anchors()

        current_task_classes = list(self._task_pool.keys())

        if self.use_real_buffer:
            train_x, train_y = self._build_training_tensors_buffered()
        else:
            train_x, train_y = self._build_task_pool_tensors()

        if train_x.numel() == 0:
            self._task_pool.clear()
            return

        cvae = self._ensure_cvae()

        # Take a snapshot of the current CVAE as teacher BEFORE updating.
        teacher: Optional[EmbeddingCVAE] = None
        if self._cvae_trained:
            teacher = cvae.snapshot()

        # Buffer-free mode: pre-generate balanced old-class training data from
        # the teacher CVAE.  The training set passed to fit() then contains
        # exactly N real samples per current class and N synthetic samples per
        # old class, where N = max per-class count in the current task pool.
        if not self.use_real_buffer and teacher is not None:
            old_classes = [
                c
                for c in range(teacher.num_classes)
                if c not in current_task_classes
            ]
            if old_classes:
                counts = {
                    c: self._task_pool[c].size(0)
                    for c in current_task_classes
                    if self._task_pool[c].numel() > 0
                }
                n_per_old = max(counts.values()) if counts else 64
                with torch.no_grad():
                    gen_x, gen_y = teacher.sample(old_classes, n_per_old, self.device)
                if gen_x.numel() > 0:
                    train_x = torch.cat([train_x, gen_x.cpu()], dim=0)
                    train_y = torch.cat([train_y, gen_y.cpu()], dim=0)
                    if self.replay_debug:
                        logger.info(
                            f"CVAE maintain: generated {gen_x.size(0)} synthetic "
                            f"embeddings across {len(old_classes)} old classes "
                            f"({n_per_old} per class) for CVAE training."
                        )

                # Real-anchor mixing: add ref_buffer samples to CVAE training data
                # for old classes.  These real embeddings prevent the generated
                # centroid from drifting away from the true class distribution
                # across tasks (compounding-error problem).  Only the CVAE sees
                # this real data; the ROLANN classifier is never trained on it.
                if self._ref_buffer_anchor_cvae and self._ref_buffer:
                    anchor_x_parts: List[torch.Tensor] = []
                    anchor_y_parts: List[torch.Tensor] = []
                    for c in old_classes:
                        ref = self._ref_buffer.get(c)
                        if ref is not None and ref.numel() > 0:
                            # ref_buffer already stores embeddings in the same
                            # normalisation space as _task_pool (processed via
                            # _normalize in add_task_samples).
                            anchor_x_parts.append(ref.cpu())
                            anchor_y_parts.append(
                                torch.full((ref.size(0),), c, dtype=torch.long)
                            )
                    if anchor_x_parts:
                        anc_x = torch.cat(anchor_x_parts, dim=0)
                        anc_y = torch.cat(anchor_y_parts, dim=0)
                        train_x = torch.cat([train_x, anc_x], dim=0)
                        train_y = torch.cat([train_y, anc_y], dim=0)
                        if self.replay_debug:
                            logger.info(
                                f"CVAE maintain: added {anc_x.size(0)} real "
                                f"ref-buffer anchors across {len(anchor_x_parts)} "
                                f"old classes for centroid stabilisation."
                            )

        x = self._normalize(train_x).to(self.device)
        y = train_y.to(self.device)

        means_on_device = {
            c: m.to(self.device) for c, m in self.class_means.items()
        }

        # Build real_eval dict for quality monitoring.
        if self.use_real_buffer:
            real_eval = {
                int(cls): self._normalize(tensor).to(self.device)
                for cls, tensor in self.real_buffer.items()
                if tensor.numel() > 0
            }
        else:
            # Use current task pool as quality reference (cleared after fit).
            real_eval = {
                int(cls): self._normalize(pool).to(self.device)
                for cls, pool in self._task_pool.items()
                if pool.numel() > 0
            }

        # In buffer-free mode the training data is already balanced, so no
        # additional internal gen_replay_ratio mixing is needed.
        effective_gen_ratio = self.gen_replay_ratio if self.use_real_buffer else 0.0

        self.last_cvae_fit_summary = cvae.fit(
            x,
            y,
            beta=self.beta,
            gen_replay_ratio=effective_gen_ratio,
            teacher=teacher,
            teacher_kl_weight=self.teacher_kl_weight if self.use_teacher_kl else 0.0,
            class_means=means_on_device,
            stats_loss_weight=self.stats_loss_weight,
            feature_matching_weight=self.feature_matching_weight,
            current_task_classes=current_task_classes,
            real_by_class=real_eval,
            max_steps=self.train_max_steps,
            min_steps=self.train_min_steps,
            eval_every=self.train_eval_every,
            patience=self.train_patience,
            recon_cosine_stop=self.recon_cosine_stop,
            # In buffer-free mode commit fully; generation quality gate is
            # still evaluated but does not determine whether CVAE is used.
            gen_cosine_stop=self.gen_cosine_stop if self.use_real_buffer else 0.0,
            gen_eval_samples_per_class=self.gen_eval_samples_per_class,
        )

        if self.replay_debug:
            logger.info(f"CVAE fit: {self.last_cvae_fit_summary}")
            if self.use_real_buffer and not self._cvae_replay_ready():
                logger.warning(
                    "CVAE recon below cvae_recon_cosine_stop — "
                    "replay will fall back to real_buffer upsampling"
                )

        self._cvae_trained = True
        self._task_pool.clear()

    def get_memory_samples(
        self,
        classes: List[int],
        buffer_state: Optional[Dict[int, torch.Tensor]] = None,
        samples_per_class: Optional[int] = None,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Return replay embeddings for the requested *classes*.

        Buffer-free mode (``use_real_buffer=False``)
            Always generates exactly *samples_per_class* embeddings per class
            from the CVAE.  No fallback to stored reals exists.  If the CVAE
            has not been trained yet (task 0, where no replay is requested),
            returns empty tensors.

        Real-buffer mode (``use_real_buffer=True``) — original behaviour
            Prefers stored real exemplars; uses the CVAE to fill up to
            *samples_per_class* when the quality gate is met.
        """
        # Buffer-free path.
        if not self.use_real_buffer:
            if not self._cvae_trained or self._cvae is None:
                return (
                    torch.empty(0),
                    torch.empty(0, dtype=torch.long),
                )
            n_per_class = (
                samples_per_class
                if samples_per_class and samples_per_class > 0
                else self.generated_per_class
            )
            with torch.no_grad():
                emb, lbl = self._cvae.sample(classes, n_per_class, self.device)
            if emb.numel() == 0:
                return torch.empty(0), torch.empty(0, dtype=torch.long)
            emb_cpu = self._normalize(emb.cpu())
            lbl_cpu = lbl.cpu()
            self.last_replay_sources = {
                c: {"cvae": n_per_class, "real": 0, "anchor": 0, "stats": 0}
                for c in classes
                if c < self._cvae.num_classes
            }
            return emb_cpu, lbl_cpu

        # Real-buffer path (original behaviour).
        if buffer_state is not None:
            x, y = self._samples_from_state(buffer_state, classes)
            if samples_per_class is not None and x.numel() > 0:
                x, y = upsample_per_class(x, y, samples_per_class)
            return x, y

        want_cvae = bool(getattr(self, "replay_generate_from_cvae", False))
        generate_from_cvae = want_cvae and self._cvae_replay_ready()
        if want_cvae and not generate_from_cvae and self.replay_debug:
            logger.warning(
                "Skipping CVAE replay (quality gate); using real_buffer upsampling"
            )

        parts_x, parts_y = [], []
        self.last_replay_sources = {}

        for c in classes:
            cx, cy, src = self._collect_class_samples(
                c,
                n_samples=samples_per_class,
                generate_from_cvae=generate_from_cvae,
            )
            if cx.numel() == 0:
                continue
            parts_x.append(cx)
            parts_y.append(cy)
            self.last_replay_sources[c] = src

        if not parts_x:
            return torch.empty(0), torch.empty(0, dtype=torch.long)

        return torch.cat(parts_x, dim=0), torch.cat(parts_y, dim=0)

    # ------------------------------------------------------------------
    # Generation quality measurement
    # ------------------------------------------------------------------

    def measure_generation_quality(
        self,
        classes: Optional[List[int]] = None,
        n_gen_per_class: int = 64,
    ) -> Dict[str, Any]:
        """
        Compare CVAE-generated embeddings to the measurement-only reference
        buffer and return distribution-level metrics.

        This method is **never** called during training — it is a diagnostic
        tool only.  Call it after ``maintain()`` to assess whether the CVAE
        is producing realistic samples for each class.

        Parameters
        ----------
        classes :
            Classes to evaluate.  Defaults to all classes present in the
            reference buffer.  Classes without reference data are skipped.
        n_gen_per_class :
            How many samples to generate per class for comparison.

        Returns
        -------
        Dict with keys ``"per_class"`` and ``"agg"``.  See
        ``cvae_metrics.per_class_generation_report`` for field descriptions.
        Returns ``{}`` if the CVAE has not been trained yet or the reference
        buffer is empty.
        """
        if not self._cvae_trained or self._cvae is None:
            return {}
        if not self._ref_buffer:
            return {}

        if classes is None:
            classes = [c for c in self._ref_buffer if self._ref_buffer[c].numel() > 0]
        else:
            classes = [c for c in classes if c in self._ref_buffer and self._ref_buffer[c].numel() > 0]

        if not classes:
            return {}

        # Generate from CVAE for every requested class.
        with torch.no_grad():
            gen_emb, gen_lbl = self._cvae.sample(classes, n_gen_per_class, self.device)

        gen_emb = gen_emb.cpu()
        gen_lbl = gen_lbl.cpu()

        # Build per-class dicts in the same normalisation space as the CVAE
        # was trained on (i.e. the same space as the reference buffer entries,
        # which were stored by add_task_samples() after _normalize()).
        real_by_class: Dict[int, torch.Tensor] = {
            c: self._ref_buffer[c].float() for c in classes
        }
        gen_by_class: Dict[int, torch.Tensor] = {}
        for c in classes:
            mask = gen_lbl == c
            if mask.any():
                gen_by_class[c] = gen_emb[mask].float()

        return _generation_report(real_by_class, gen_by_class)

    # ------------------------------------------------------------------
    # Training-tensor builders
    # ------------------------------------------------------------------

    def _build_task_pool_tensors(self) -> Tuple[torch.Tensor, torch.Tensor]:
        """Return normalised current-task embeddings from ``_task_pool``."""
        xs, ys = [], []
        for cls, pool in self._task_pool.items():
            if pool.numel() == 0:
                continue
            xs.append(self._normalize(pool))
            ys.append(torch.full((pool.size(0),), int(cls), dtype=torch.long))
        if not xs:
            return torch.empty(0, self.embed_dim), torch.empty(0, dtype=torch.long)
        return torch.cat(xs, dim=0), torch.cat(ys, dim=0)

    def _build_training_tensors_buffered(
        self,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Build CVAE training data in real-buffer mode.

        Uses ``real_buffer`` when ``train_on == 'real_buffer'`` (default),
        otherwise combines ``_task_pool`` + herding anchors.
        """
        xs, ys = [], []

        if self.train_on == "real_buffer":
            for cls in sorted(self.real_buffer.keys()):
                pool = self.real_buffer[cls]
                if pool.numel() == 0:
                    continue
                xs.append(self._normalize(pool))
                ys.append(
                    torch.full((pool.size(0),), int(cls), dtype=torch.long)
                )
        else:
            for cls, pool in self._task_pool.items():
                if pool.numel() == 0:
                    continue
                xs.append(self._normalize(pool))
                ys.append(
                    torch.full((pool.size(0),), int(cls), dtype=torch.long)
                )
            for cls, anc in self.anchors.items():
                if anc.numel() == 0:
                    continue
                a = self._normalize(anc)
                xs.append(a)
                ys.append(
                    torch.full((a.size(0),), int(cls), dtype=torch.long)
                )

        if not xs:
            return torch.empty(0, self.embed_dim), torch.empty(0, dtype=torch.long)

        return torch.cat(xs, dim=0), torch.cat(ys, dim=0)

    # ------------------------------------------------------------------
    # Per-class sample collection (real-buffer path only)
    # ------------------------------------------------------------------

    def _can_generate_class(self, cls: int) -> bool:
        return (
            self._cvae is not None
            and self._cvae_trained
            and cls < self._cvae.num_classes
        )

    def _collect_class_samples(
        self,
        cls: int,
        n_samples: Optional[int] = None,
        generate_from_cvae: bool = False,
    ) -> Tuple[torch.Tensor, torch.Tensor, Dict[str, int]]:
        """Build replay rows for one class (real-buffer path)."""
        sources = {"real": 0, "anchor": 0, "cvae": 0, "stats": 0}

        if (
            generate_from_cvae
            and n_samples is not None
            and n_samples > 0
            and self._can_generate_class(cls)
        ):
            with torch.no_grad():
                gx, _ = self._cvae.sample([cls], n_samples, self.device)
            if gx.numel() > 0:
                x = self._normalize(gx.cpu())
                y = torch.full((x.size(0),), cls, dtype=torch.long)
                sources["cvae"] = x.size(0)
                return x, y, sources

        parts_x: List[torch.Tensor] = []

        if cls in self.real_buffer and self.real_buffer[cls].numel() > 0:
            real = self._normalize(self.real_buffer[cls])
            parts_x.append(real)
            sources["real"] = real.size(0)

        if not parts_x and cls in self.anchors and self.anchors[cls].numel() > 0:
            ax = self._normalize(self.anchors[cls])
            parts_x.append(ax)
            sources["anchor"] = ax.size(0)

        if not parts_x and cls in self.class_means:
            n_fallback = n_samples if n_samples and n_samples > 0 else 1
            parts_x.append(self._sample_from_stats(cls, n_fallback))
            sources["stats"] = n_fallback

        if not parts_x:
            return (
                torch.empty(0, self.embed_dim),
                torch.empty(0, dtype=torch.long),
                sources,
            )

        x = torch.cat(parts_x, dim=0)
        y = torch.full((x.size(0),), cls, dtype=torch.long)

        if n_samples is not None and n_samples > 0 and x.size(0) != n_samples:
            x, y = upsample_per_class(x, y, n_samples)

        return x, y, sources

    def _sample_from_stats(self, cls: int, n: int) -> torch.Tensor:
        mu = self.class_means[cls]
        var = self.class_vars.get(cls, torch.ones_like(mu) * 1e-4)
        samples = mu.unsqueeze(0) + torch.randn(n, mu.numel()) * var.sqrt().unsqueeze(0)
        return self._normalize(samples)

    def _samples_from_state(
        self, state: Dict[int, torch.Tensor], classes: List[int]
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        valid = [c for c in classes if c in state]
        if not valid:
            return torch.empty(0), torch.empty(0, dtype=torch.long)
        embeddings = torch.cat([self._normalize(state[c]) for c in valid])
        labels = torch.cat(
            [
                torch.full((len(state[c]),), c, dtype=torch.long)
                for c in valid
            ]
        )
        return embeddings, labels

    # ------------------------------------------------------------------
    # Inspection helpers
    # ------------------------------------------------------------------

    def get_replay_source_summary(self) -> Dict[int, Dict[str, int]]:
        return dict(self.last_replay_sources)

    def get_buffer_state(self) -> Dict[int, torch.Tensor]:
        return {cls: t.clone() for cls, t in self.real_buffer.items()}

    def get_class_distribution(
        self, buffer: Optional[Dict[int, torch.Tensor]] = None
    ) -> Dict[int, int]:
        source = buffer if buffer is not None else self.real_buffer
        return {c: len(t) for c, t in source.items()}

    def __len__(self) -> int:
        if self.use_real_buffer:
            return sum(t.size(0) for t in self.real_buffer.values())
        # Buffer-free: no stored embeddings; length is 0 by design.
        return 0
